### ISSUE TITLE
Wrong definition of owner side in Doctrine2 Many to Many relation

### ISSUE THREAD

**Issue by shirshir** [Atlantic18/ORMCheatSheet#2]
http://ormcheatsheet.com/#manytomany

According to http://doctrine-orm.readthedocs.org/en/latest/reference/unitofwork-associations.html the owner side of a ManyToMany relation has to use `inversedBy`.

<blockquote>
The owning side has to use the `inversedBy` attribute of the OneToOne, ManyToOne, or ManyToMany mapping declaration. The `inversedBy` attribute contains the name of the association-field on the inverse-side.
</blockquote>

**Comment by ludekvodicka** [comment]
Hi,
thanks for feedback, you're right. We wrongly swapped the inverse and owner side.
It should be fixed now

**Comment by shirshir** [comment]
Thanks! :smiley:

**Comment by ludekvodicka** [comment]
You're welcome, thank you too.

Ludek

## 

Ludek Vodicka

# ORM Designer | Visual editor for ORM frameworks

Develop, document and design at the same time
Full support of  Doctrine, Propel, Symfony and CakePHP

http://www.orm-designer.com

2014-10-30 11:28 GMT+01:00 shirshir notifications@github.com:
